### ISSUE TITLE
What license is this project released under?

### ISSUE THREAD

**Issue by megalon** [Chikanz/PolyRobots#1]
Hello, 

I would like to use your implementation of the PolyPizza API manager in my own Unity project, but I don't know what license this project has.

What license is this project released under?

Thanks!

**Comment by Chikanz** [comment]
Hey megalon! Good catch, I've added the MIT license to the repo. Feel free to do whatever you want with it :)

**Comment by megalon** [comment]
Great!

That's perfect, thanks
